**

!BiometricoLunch-/
!BiometricoLunch-/package.json
!BiometricoLunch-/pnpm-lock.yaml
!BiometricoLunch-/pnpm-workspace.yaml
!BiometricoLunch-/apps/
!BiometricoLunch-/apps/web/
!BiometricoLunch-/apps/web/**

**/.env
**/node_modules
**/dist
**/*.tsbuildinfo
**/*.log
