**

!BiometricoLunch-/
!BiometricoLunch-/package.json
!BiometricoLunch-/pnpm-lock.yaml
!BiometricoLunch-/pnpm-workspace.yaml
!BiometricoLunch-/apps/
!BiometricoLunch-/apps/api/
!BiometricoLunch-/apps/api/**

!Csharp/
!Csharp/MarcacionComida.BiometricMatcher/
!Csharp/MarcacionComida.BiometricMatcher/**

!SDK/
!SDK/DP_Bio_SDK_3.6.0.307/
!SDK/DP_Bio_SDK_3.6.0.307/SDK/
!SDK/DP_Bio_SDK_3.6.0.307/SDK/x64/
!SDK/DP_Bio_SDK_3.6.0.307/SDK/x64/**
!SDK/DP_Bio_SDK_3.6.0.307/RTE/
!SDK/DP_Bio_SDK_3.6.0.307/RTE/x64/
!SDK/DP_Bio_SDK_3.6.0.307/RTE/x64/**

**/.env
**/node_modules
**/dist
**/bin
**/obj
**/*.user
**/*.log
